# Generated by Django 3.2.25 on 2025-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='助手名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用模型')),
                ('is_memory', models.BooleanField(default=True, verbose_name='是否启动记忆')),
                ('prompt_template', models.TextField(blank=True, null=True, verbose_name='提示词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '助手',
                'verbose_name_plural': '助手',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
