# Generated by Django 5.1.7 on 2025-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantsConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='用户ID')),
                ('name', models.CharField(max_length=100, verbose_name='助手名称')),
                ('relationship', models.CharField(max_length=255, verbose_name='助手与用户的关系')),
                ('nickname', models.CharField(max_length=255, verbose_name='助手对用户的称呼')),
                ('personality', models.CharField(max_length=255, verbose_name='助手性格')),
                ('greeting', models.CharField(blank=True, max_length=255, null=True, verbose_name='助手问候语')),
                ('dialogue_style', models.CharField(blank=True, max_length=255, null=True, verbose_name='助手说话的方式')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公共配置')),
            ],
            options={
                'verbose_name': '助手配置',
                'verbose_name_plural': '助手配置',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssistantTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='助手模板名称')),
                ('prompt_template', models.TextField(blank=True, null=True, verbose_name='提示词')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否是默认模版')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '助手模板',
                'verbose_name_plural': '助手模板',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UsersAssistantTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='用户ID')),
                ('name', models.CharField(max_length=100, verbose_name='助手模板名称')),
                ('prompt_template', models.TextField(blank=True, null=True, verbose_name='提示词')),
                ('is_premium_template', models.BooleanField(default=False, verbose_name='是否付费模版')),
                ('is_default', models.BooleanField(default=True, verbose_name='是否是默认模版')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户助手模板',
                'verbose_name_plural': '用户助手模板',
                'ordering': ['-id', 'name'],
            },
        ),
    ]
