# Generated by Django 3.2.25 on 2025-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模型名字')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('temperature', models.FloatField(default=0.7, verbose_name='灵活度')),
                ('base_url', models.URLField(blank=True, verbose_name='模型URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
