# Generated by Django 5.1.7 on 2025-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engines',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模型密钥'),
        ),
    ]
