# Generated by Django 3.2.25 on 2025-03-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='UserCenter的用户ID', verbose_name='用户ID')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('notify_time', models.CharField(max_length=5, verbose_name='通知时间')),
                ('days_remaining', models.IntegerField(default=21, verbose_name='剩余天数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='上次发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '定时通知设置',
                'verbose_name_plural': '定时通知设置',
                'ordering': ['-created_at'],
            },
        ),
    ]
