# Generated by Django 3.2.25 on 2025-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='UserCenter的用户ID', verbose_name='用户ID')),
                ('app_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='具体苹果的应用')),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('original_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_data', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='处理过程中的备注信息', null=True)),
            ],
            options={
                'verbose_name': '苹果内购',
                'verbose_name_plural': '苹果内购',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user_id', 'is_active'], name='purchase_pu_user_id_3b6099_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['original_transaction_id'], name='purchase_pu_origina_c057f5_idx'),
        ),
    ]
