# Generated by Django 3.2.25 on 2025-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('INITIAL_BUY', '用户首次订阅'), ('DID_CHANGE_RENEWAL_STATUS', '订阅状态更改'), ('INTERACTIVE_RENEWAL', '通过互动方式续订订阅'), ('DID_CHANGE_RENEWAL_PREF', '订阅计划更改'), ('CONSUMPTION_REQUEST', '发起退款'), ('CANCEL', '退订'), ('DID_FAIL_TO_RENEW', '账单问题而未能续订的订阅'), ('DID_RECOVER', '指示之前未能续订的已过期订阅成功自动续订'), ('DID_RENEW', '客户的订阅已成功自动续订至新的交易周期'), ('PRICE_INCREASE_CONSENT', '用户同意自动续订的价格调整，继续续订'), ('REFUND', '已成功退还了应用内购买的消耗品、非消耗品或非续订订阅的交易'), ('REVOKE', '用户通过家庭共享获得的内购项目不再通过共享可用')], max_length=255, null=True, verbose_name='订单通知类型'),
        ),
    ]
