# Generated by Django 3.2.25 on 2025-03-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleappconfiguration',
            name='shared_secret',
            field=models.CharField(default='', help_text='内购密码', max_length=20, verbose_name='shared_secret'),
        ),
    ]
