# Generated by Django 3.2.25 on 2025-03-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_appleappconfiguration_shared_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleappconfiguration',
            name='shared_secret',
            field=models.CharField(default='', help_text='内购密码', max_length=255, verbose_name='shared_secret'),
        ),
    ]
