# Generated by Django 3.2.25 on 2025-03-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_alter_appleappconfiguration_shared_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleappconfiguration',
            name='admin_token',
            field=models.CharField(default='', help_text='管理员token', max_length=255, verbose_name='shared_secret'),
        ),
    ]
